### ISSUE TITLE
Duplicate interface

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#10]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/footer/footer.interface.ts#L1

1. Couldn't you have used these interfaces for the header as well?
2. Like add the logo support and then perhaps add and enum called LOCATION with has the options (header,footer)?
3. That way its easier to maintain consistency

**Comment by spockula** [comment]
used the one interface for header and footer, added logo support for both
