### ISSUE TITLE
Too much stub code

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#11]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/subscribe/subscribe.component.ts#L9

1. It looks to me like this doesn't actually do anything?
2. Don't you have code that you could have ported over from the other branch to satisfy this functionality?

**Comment by spockula** [comment]
this is a new feature, in the other branch, our subscription was handled via a mailchimp script, i only added this component to follow the principles we had started with on this branch. At the moment we are not subscribing to anything, should i remove completely?
