### ISSUE TITLE
No Click handlers on the Card

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#12]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/nftcard/nftcard.component.html#L7

1. You still have not added any click handlers to this card
2. A user should be able to click to place a bid, see the creators profile etc
3. None of that exists here

**Comment by spockula** [comment]
click handlers added destination pages not yet implemented so router points to home, like and follow events also added to card
