### ISSUE TITLE
Shouldn't you be using media-queries for this?

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#13]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/carousel/carousel.component.ts#L24

**Comment by spockula** [comment]
this comes from p-carousel, a component from primeNg, they are optional settings for the component, Not needed at the moment so removed.
