### ISSUE TITLE
Your Slider only supports Auction types

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#7]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/slider/slider.component.html#L13

1. You are supposed to add an  ngSwitch to check what 'type' of slide is being rendered e.g. Aution, Blog, Artwork etc.
2. Based on this you have various switch cases to account for the different types
3. Although we only have designs for the Auction so far, adding this now will make it easier to update in future

**Comment by spockula** [comment]
slider component now works with ngSwitch, supports types "Auction", "Artwork", "Collection", "Creator"
