### ISSUE TITLE
Non Dynamic fields

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#8]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/header/header.component.html#L14 and Line 36

1. The purpose of the logo being dynamic is so that if the design is updated on the server, we can point to a new one
2. The purpose of the wallet buttons being dynamic, is so that we can change the buttons that show depending on the user state e.g. When they are not logged in, its "Connect Wallet", when they are its "the Wallet address" and then we can even show different menu options based on that.
3. You haven't done this as instructed and this WILL cause problems later

**Comment by spockula** [comment]
1. Logo and button information is now fetched from server
