### ISSUE TITLE
Follow naming Conventions

### ISSUE THREAD

**Issue by femiashiru1** [xendbit/AssetManagerUI2#9]
https://github.com/xendbit/AssetManagerUI2/blob/84a89f78e74fd3ea99dacc33829816fab4fb906d/src/app/core/components/header/header.interface.ts#L1

1. ALL interfaces should follow this convention I<capitalised name of the interface> e.g. INavbar not navbar
2. make sure you change ALL interfaces you have created to this standard

**Comment by spockula** [comment]
Interfaces have all been updated to follow this convention
